var config         = require('../../../../config/config.js');

var Promise        = require('bluebird');

var path           = require("path");

var async          = require('asyncawait/async');

var await          = require('asyncawait/await');

var index          = `${config.server.context}/api/networkOwner/sign/country`;

var CountryServ    = require("./country.service");

var Country    	   = require("./country.schema");

var AuthCognitoServ       = require('../../../../components/auth/cognito/auth');

var join = link => path.join(index, link != null ? link : "");

module.exports = function(app) {

  app.post(join('/getCountries'), getCountries);

};

var getCountries = async(function(req, res) {
  var { country } = req.body
  try {
    var countries = await(CountryServ.getCountries(country))
    return res.send(countries)
  } catch(err) {
    return res.status(400).send(err) 
  }
})

// var find = async(function(req, res) {
// 	var query = req.params
// 	try {
// 		var result = await(CountryServ.find(query))
// 		res.send(result)
// 	} catch(err) {
// 		res.status(400).send(err) 
// 	}
// })

var installCountry = async(function() {
  var country = []
  country.push({name: 'Afghanistan'})
  country.push({name: 'Albania'})
  country.push({name: 'Algeria'})
  country.push({name: 'Andorra'})
  country.push({name: 'Angola'})
  country.push({name: 'Anguilla'})
  country.push({name: 'Antigua & Barbuda'})
  country.push({name: 'Argentina'})
  country.push({name: 'Armenia'})
  country.push({name: 'Australia'})
  country.push({name: 'Austria'})
  country.push({name: 'Azerbaijan'})
  country.push({name: 'Bahamas'})
  country.push({name: 'Bahrain'})
  country.push({name: 'Bangladesh'})
  country.push({name: 'Barbados'})
  country.push({name: 'Belarus'})
  country.push({name: 'Belgium'})
  country.push({name: 'Belize'})
  country.push({name: 'Benin'})
  country.push({name: 'Bermuda'})
  country.push({name: 'Bhutan'})
  country.push({name: 'Bolivia'})
  country.push({name: 'Bosnia & Herzegovina'})
  country.push({name: 'Botswana'})
  country.push({name: 'Brazil'})
  country.push({name: 'Brunei Darussalam'})
  country.push({name: 'Bulgaria'})
  country.push({name: 'Burkina Faso'})
  country.push({name: 'Myanmar/Burma'})
  country.push({name: 'Burundi'})
  country.push({name: 'Cambodia'})
  country.push({name: 'Cameroon'})
  country.push({name: 'Canada'})
  country.push({name: 'Cape Verde'})
  country.push({name: 'Cayman Islands'})
  country.push({name: 'Central African Republic'})
  country.push({name: 'Chad'})
  country.push({name: 'Chile'})
  country.push({name: 'China'})
  country.push({name: 'Colombia'})
  country.push({name: 'Comoros'})
  country.push({name: 'Congo'})
  country.push({name: 'Costa Rica'})
  country.push({name: 'Croatia'})
  country.push({name: 'Cuba'})
  country.push({name: 'Cyprus'})
  country.push({name: 'Czech Republic'})
  country.push({name: 'Democratic Republic of the Congo'})
  country.push({name: 'Denmark'})
  country.push({name: 'Djibouti'})
  country.push({name: 'Dominica'})
  country.push({name: 'Dominican Republic'})
  country.push({name: 'Ecuador'})
  country.push({name: 'Egypt'})
  country.push({name: 'El Salvador'})
  country.push({name: 'Equatorial Guinea'})
  country.push({name: 'Eritrea'})
  country.push({name: 'Estonia'})
  country.push({name: 'Ethiopia'})
  country.push({name: 'Fiji'})
  country.push({name: 'Finland'})
  country.push({name: 'France'})
  country.push({name: 'French Guiana'})
  country.push({name: 'Gabon'})
  country.push({name: 'Gambia'})
  country.push({name: 'Georgia'})
  country.push({name: 'Germany'})
  country.push({name: 'Ghana'})
  country.push({name: 'Great Britain'})
  country.push({name: 'Greece'})
  country.push({name: 'Grenada'})
  country.push({name: 'Guadeloupe'})
  country.push({name: 'Guatemala'})
  country.push({name: 'Guinea'})
  country.push({name: 'Guinea-Bissau'})
  country.push({name: 'Guyana'})
  country.push({name: 'Haiti'})
  country.push({name: 'Honduras'})
  country.push({name: 'Hungary'})
  country.push({name: 'Iceland'})
  country.push({name: 'India'})
  country.push({name: 'Indonesia'})
  country.push({name: 'Iran'})
  country.push({name: 'Iraq'})
  country.push({name: 'Israel and the Occupied Territories'})
  country.push({name: 'Italy'})
  country.push({name: "Ivory Coast (Cote d'Ivoire)"})
  country.push({name: 'Jamaica'})
  country.push({name: 'Japan'})
  country.push({name: 'Jordan'})
  country.push({name: 'Kazakhstan'})
  country.push({name: 'Kenya'})
  country.push({name: 'Kosovo'})
  country.push({name: 'Kuwait'})
  country.push({name: 'Kyrgyz Republic (Kyrgyzstan)'})
  country.push({name: 'Laos'})
  country.push({name: 'Latvia'})
  country.push({name: 'Lebanon'})
  country.push({name: 'Lesotho'})
  country.push({name: 'Liberia'})
  country.push({name: 'Libya'})
  country.push({name: 'Liechtenstein'})
  country.push({name: 'Lithuania'})
  country.push({name: 'Luxembourg'})
  country.push({name: 'Republic of Macedonia'})
  country.push({name: 'Madagascar'})
  country.push({name: 'Malawi'})
  country.push({name: 'Malaysia'})
  country.push({name: 'Maldives'})
  country.push({name: 'Mali'})
  country.push({name: 'Malta'})
  country.push({name: 'Martinique'})
  country.push({name: 'Mauritania'})
  country.push({name: 'Mauritius'})
  country.push({name: 'Mayotte'})
  country.push({name: 'Mexico'})
  country.push({name: 'Moldova, Republic of'})
  country.push({name: 'Monaco'})
  country.push({name: 'Mongolia'})
  country.push({name: 'Montenegro'})
  country.push({name: 'Montserrat'})
  country.push({name: 'Morocco'})
  country.push({name: 'Mozambique'})
  country.push({name: 'Namibia'})
  country.push({name: 'Nepal'})
  country.push({name: 'Netherlands'})
  country.push({name: 'New Zealand'})
  country.push({name: 'Nicaragua'})
  country.push({name: 'Niger'})
  country.push({name: 'Nigeria'})
  country.push({name: 'Korea, Democratic Republic of (North Korea)'})
  country.push({name: 'Norway'})
  country.push({name: 'Oman'})
  country.push({name: 'Pacific Islands'})
  country.push({name: 'Pakistan'})
  country.push({name: 'Panama'})
  country.push({name: 'Papua New Guinea'})
  country.push({name: 'Paraguay'})
  country.push({name: 'Peru'})
  country.push({name: 'Philippines'})
  country.push({name: 'Poland'})
  country.push({name: 'Portugal'})
  country.push({name: 'Puerto Rico'})
  country.push({name: 'Qatar'})
  country.push({name: 'Reunion'})
  country.push({name: 'Romania'})
  country.push({name: 'Russian Federation'})
  country.push({name: 'Rwanda'})
  country.push({name: 'Saint Kitts and Nevis'})
  country.push({name: 'Saint Lucia'})
  country.push({name: "Saint Vincent's & Grenadines"})
  country.push({name: 'Samoa'})
  country.push({name: 'Sao Tome and Principe'})
  country.push({name: 'Saudi Arabia'})
  country.push({name: 'Senegal'})
  country.push({name: 'Serbia'})
  country.push({name: 'Seychelles'})
  country.push({name: 'Sierra Leone'})
  country.push({name: 'Singapore'})
  country.push({name: 'Slovak Republic (Slovakia)'})
  country.push({name: 'Slovenia'})
  country.push({name: 'Solomon Islands'})
  country.push({name: 'Somalia'})
  country.push({name: 'South Africa'})
  country.push({name: 'Korea, Republic of (South Korea)'})
  country.push({name: 'South Sudan'})
  country.push({name: 'Spain'})
  country.push({name: 'Sri Lanka'})
  country.push({name: 'Sudan'})
  country.push({name: 'Suriname'})
  country.push({name: 'Swaziland'})
  country.push({name: 'Sweden'})
  country.push({name: 'Switzerland'})
  country.push({name: 'Syria'})
  country.push({name: 'Tajikistan'})
  country.push({name: 'Tanzania'})
  country.push({name: 'Thailand'})
  country.push({name: 'Timor Leste'})
  country.push({name: 'Togo'})
  country.push({name: 'Trinidad & Tobago'})
  country.push({name: 'Tunisia'})
  country.push({name: 'Turkey'})
  country.push({name: 'Turkmenistan'})
  country.push({name: 'Turks & Caicos Islands'})
  country.push({name: 'Uganda'})
  country.push({name: 'Ukraine'})
  country.push({name: 'United Arab Emirates'})
  country.push({name: 'United States of America (USA)'})
  country.push({name: 'Uruguay'})
  country.push({name: 'Uzbekistan'})
  country.push({name: 'Venezuela'})
  country.push({name: 'Vietnam'})
  country.push({name: 'Virgin Islands (UK)'})
  country.push({name: 'Virgin Islands (US)'})
  country.push({name: 'Yemen'})
  country.push({name: 'Zambia'})
  country.push({name: 'Zimbabwe'})
  for (var i = 0; i < country.length; i++) {
    var _country = new Country(country[i])
    var [ existCountry ] = await(Country.find({name: country[i].name}))
    if (!existCountry) {
      _country.save()
    }
  }
})

installCountry()